export const NEIGHBORHOODS = [
  'Bela Vista',
  'Centro',
  'Cidade Alta',
  'Cidade Baixa',
  'Fátima',
  'Bandeira Branca',
  'São Francisco',
  'São Thomás',
  'Lago Parque Clube',
  "Passo D'Areia",
  'Princesa Isabel',
  'Quininho',
  'Olaria',
  'Beira Rio',
  'Lindos Ares',
  'Padre Reus',
  'Capororóca',
  'Parque de Exposições',
  'Residencial Bela Vista',
  'Passo da Cruz',
  'Porto do Conde',
]
