export const NEIGHBORHOODS = [
  'Bairro 1',
  'Bela Vista',
  'Centro',
  'Cidade Alta',
  'Cidade Baixa',
  'Fátima',
  'Bandeira Branca',
  'Santo Antônio',
  'Santa Rita',
  'São Francisco',
  'São Thomás',
  'Lago Parque Clube',
  "Passo D'Areia",
  'Princesa Isabel',
  'Quininho',
  'Vila Nova',
  'Medianeira',
  'Olaria',
  'Estaleiro',
  'Beira Rio',
  'Lindos Ares',
  'Padre Reus',
  'Piratini',
  'Sol Nascente',
  'Capororóca',
  'Parque de Exposições',
  'Residencial Bela Vista',
  'Passo da Cruz',
  'Porto do Conde',
]
